services:
  servers:
    build: .
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - konzek

  nginx_1:
    container_name: nginx_proxy_1
    build: ./nginx
    ports:
      - "81:80"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/keepalived-master.conf:/etc/keepalived/keepalived.conf"
    networks:
      - konzek

  nginx_2:
    container_name: nginx_proxy_2
    build: ./nginx
    ports:
      - "80:80"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/keepalived-backup.conf:/etc/keepalived/keepalived.conf"
    networks:
      - konzek

networks:
  konzek:
    driver: bridge